- hosts: app
  tasks:

  - name: "Delete existing pod and deployment"
    shell: "kubectl delete pod myapp --ignore-not-found && kubectl delete deployments myapp --ignore-not-found"

  - name: "Copy service yaml file"
    copy:
      src: myapp.yaml
      dest: /home/vagrant/myapp.yaml

  - name: "Create pod"
    shell: "kubectl run myapp --image=ttl.sh/fvaldes-docker-ruby-hw"

  - name: "Refresh service"
    shell: "kubectl apply -f myapp.yaml"

  - name: "Create deployments"
    shell: "kubectl create deployment myapp --image=ttl.sh/fvaldes-docker-ruby-hw && kubectl scale --replicas=2 deployment/myapp"

